PUT http://localhost:3003/api/blogs/61d37e06e9fdefddbf79529f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvIiwiaWQiOiI2MWQzNzk5MzE2NjUyYmI5MWI1NDg0YTQiLCJpYXQiOjE2NDEyNDk2OTB9.iiEhPnHmfi93ZCvcczRQgnCUHwgAIN9nyz6aDLJYxAc

{
  "title": "Mikon päivitetty blogi",
  "likes": 70
}